# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://toxicbbq.org'
baseurl: ''
title: 'Toxic BBQ'
description: ''
permalink: pretty
logo: "/assets/logos/jack.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Volunteering
  url: /volunteering/
- title: Updates
  url: /updates/
- title: Archive
  url: /archive/
- title: Gallery
  url: /gallery/
- title: Donate
  url: https://donate.toxicbbq.org

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Updates
    output: true
    description: "Information about Toxic BBQ."
    feature_image: "/assets/photos/updates_banner.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  32: '/assets/logos/favicon.ico'

# Fonts
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&display=swap

# Images
mini_magick:
  photoFolders:
    source: assets/images/gallery
    destination: thumbnails/assets/images/gallery
    resize: "320x240^"
    gravity: "center"
    extent: "320x240"
